version: "3.9"
services:
  placita:
    restart: always
    container_name: placita
    image: index.docker.io/starlightromero/placita-placita
    env_file:
      - .env
    networks:
      - placita-network

  nginx:
    restart: always
    container_name: nginx
    image: index.docker.io/starlightromero/placita-nginx
    ports:
      - 80:80
      - 443:443
    # volumes:
    #   - /root/certs-data/:/data/letsencrypt/
    #   - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      - placita-network
    depends_on:
      - placita

networks:
  placita-network:
    driver: bridge
